version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./api/pastries:/usr/src/app/pastries
  app:
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - api

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  import:
    build: ./api
    command: ["npm", "run", "import:pastries"]
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./pastries:/usr/src/app/pastries # Monter le répertoire des pâtisseries

volumes:
  mongo_data:
