version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017/yummyyams
      - JWT_SECRET=your_secret_key
    depends_on:
      - mongo

  app:
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - api

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
